import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styled from "@emotion/styled";

import Layout from "../src/layout/Layout";

const Home: NextPage = () => {
  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </Wrapper>
  );
};

export default Home;

const Wrapper = styled.div`
  background: #111213;
  min-height: 100vh;
  padding: 0 5rem;
`;
